import {IUser} from 'interfaces/user';

export const Users: IUser[] = [
  {_id: 1, profilePicture: 'person/1.png', username: 'Mojo', followers: [], followings: []},
  {_id: 2, profilePicture: 'person/2.png', username: 'Persnickety', followers: [], followings: []},
  {_id: 3, profilePicture: 'person/3.png', username: 'Fisticuffs', followers: [], followings: []},
  {_id: 4, profilePicture: 'person/4.png', username: 'Doldrums', followers: [], followings: []},
  {_id: 5, profilePicture: 'person/5.png', username: 'Gossamer', followers: [], followings: []},
  {_id: 6, profilePicture: 'person/6.png', username: 'Gobbledygook', followers: [], followings: []},
  {_id: 7, profilePicture: 'person/7.svg', username: 'Flummox', followers: [], followings: []},
  {_id: 8, profilePicture: 'person/1.png', username: 'Shrubbery', followers: [], followings: []},
  {_id: 9, profilePicture: 'person/2.png', username: 'Blackguard', followers: [], followings: []},
  {_id: 10, profilePicture: 'person/3.png', username: 'Highfalutin', followers: [], followings: []},
  {_id: 11, profilePicture: 'person/4.png', username: 'Daedal', followers: [], followings: []},
  {_id: 12, profilePicture: 'person/5.png', username: 'Aplomb', followers: [], followings: []},
  {_id: 13, profilePicture: 'person/6.png', username: 'Gooseflesh', followers: [], followings: []},
  {_id: 14, profilePicture: 'person/7.svg', username: 'Bumbershoot', followers: [], followings: []},
  {_id: 15, profilePicture: 'person/1.png', username: 'Snooker', followers: [], followings: []},
];

export const Posts = [
  {
    _id: 1,
    desc: '"The elevator to success is out of order. You\'ll have to use the stairs, one step at a time."',
    photo: 'post/1.jfif',
    date: '5 mins ago',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    _id: 2,
    desc: "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.",
    photo: 'post/2.jpg',
    date: '6 mins ago',
    userId: 2,
    like: 30,
    comment: 90,
  },
  {
    _id: 3,
    desc: 'I always wanted to be somebody, but now I realise I should have been more specific.',
    photo: 'post/3.jfif',
    date: '20 mins ago',
    userId: 3,
    like: 200,
    comment: 10,
  },
  {
    _id: 4,
    desc: "I am so clever that sometimes I don't understand a single word of what I am saying",
    photo: 'post/4.jfif',
    date: '1 mins ago',
    userId: 4,
    like: 10,
    comment: 10,
  },
  {
    _id: 5,
    desc: 'People say nothing is impossible, but I do nothing every day.',
    photo: 'post/5.jfif',
    date: '1 mins ago',
    userId: 5,
    like: 10,
    comment: 13,
  },
  {
    _id: 6,
    desc: 'Life is like a sewer... what you get out of it depends on what you put into it',
    photo: 'post/6.jfif',
    date: 'just now',
    userId: 6,
    like: 100,
    comment: 3,
  },
  {
    _id: 7,
    desc: 'Change is not a four letter word... but often your reaction to it is!',
    photo: 'post/4.jfif',
    date: 'just now',
    userId: 7,
    like: 100,
    comment: 40,
  },
  {
    _id: 8,
    desc: 'If you think you are too small to make a difference, try sleeping with a mosquito',
    photo: 'post/1.jfif',
    date: '1 hour ago',
    userId: 8,
    like: 32,
    comment: 1,
  },
  {
    _id: 9,
    desc: 'Bad decisions make good stories.',
    photo: 'post/2.jpg',
    date: '2 hours ago',
    userId: 9,
    like: 35,
    comment: 11,
  },
  {
    _id: 10,
    desc: "I'll probably never fully become what I wanted to be when I grew up, but that's probably because I wanted to be a ninja princess.",
    photo: 'post/3.jfif',
    date: '2 hours ago',
    userId: 10,
    like: 200,
    comment: 10,
  },
  {
    _id: 11,
    desc: 'When life gives you lemons, squirt someone in the eye.',
    photo: 'post/4.jfif',
    date: '40 mins ago',
    userId: 11,
    like: 133,
    comment: 3,
  },
  {
    _id: 12,
    desc: 'A clear conscience is a sure sign of a bad memory.',
    photo: 'post/2.jfif',
    date: '1 hour ago',
    userId: 12,
    like: 10,
    comment: 10,
  },
  {
    _id: 13,
    desc: "I didn't fail the test. I just found 100 ways to do it wrong",
    photo: 'post/3.jfif',
    date: '2 hours ago',
    userId: 13,
    like: 33,
    comment: 4,
  },
  {
    _id: 14,
    desc: "I used to think I was indecisive, but now I'm not so sure",
    photo: 'post/6.jfif',
    date: '4 hour ago',
    userId: 14,
    like: 97,
    comment: 2,
  },
  {
    _id: 15,
    desc: 'Think like a proton. Always positive.',
    photo: 'post/2.jpg',
    date: '1 day ago',
    userId: 15,
    like: 150,
    comment: 65,
  },
];
